### ISSUE TITLE
Feature Request: Hide password when sharing

### ISSUE THREAD

**Issue by Per0x** [psono/psono-server#2] opened 2018-09-13 20:19 UTC
Hello,

It would be great if we could share an ID but hide the password (and ID) so that the user who receives the element can only autofill without having the ability to see the sensitive information in clear.
On the security level, it's probably not safe because I think there would be a way to recover the password in clear with a trick by searching the cache memory for exemple, but it would be very useful when sharing an element with a trainee who will stay for a short time, or parents want to share an identifier with children for exemple.

**Comment by chickahoona** [comment] 2018-09-14 12:58
Hi Per0x, Im closing this as we manage issues and features on gitlab.

In general I understand the feature and also the wish, the problem is (as you already described) that this feature promotes a false sense of security.

The "attack vector" of searching the memory of a machine for the secret is already the extreme complicated one. There are far easier ones, so one could for example just open his chrome developer tools and read the password from the request that is sent. Or as an alternative change the type of the input field for the form from "password" to "text" where the password will be shown to you in clear text. There are a zillion of videos out there that explain it, allowing even less affine people to use those techniques:
https://www.youtube.com/results?search_query=show+hidden+passwords

Alternative measures / processes need to handle this problem (e.g. expire passwords after x days, change passwords after x days, change password once an employee leaves, Proper contracts and NDAs ...)

**Closed by chickahoona** 2018-09-14 12:58 UTC
